
//----------------------------------------------------
// The following code was generated by CUP v0.11b ${cupversion} (SVN rev )
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 40;
  public static final int PLUSPLUS = 36;
  public static final int DIVIDE = 26;
  public static final int STRINGLIT = 8;
  public static final int EQUALS = 27;
  public static final int UMINUS = 44;
  public static final int INPUT = 39;
  public static final int INTEGER = 3;
  public static final int LPAREN = 13;
  public static final int GREATER = 29;
  public static final int LESS = 31;
  public static final int MINUS = 24;
  public static final int RPAREN = 14;
  public static final int NOT = 22;
  public static final int AND = 20;
  public static final int INTLIT = 7;
  public static final int OR = 21;
  public static final int COMMA = 18;
  public static final int PLUS = 23;
  public static final int IF = 41;
  public static final int ASSIGN = 35;
  public static final int LESSEQ = 32;
  public static final int WRITEOP = 34;
  public static final int DOT = 19;
  public static final int ID = 6;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 38;
  public static final int MINUSMINUS = 37;
  public static final int TRUE = 9;
  public static final int error = 1;
  public static final int LCURLY = 11;
  public static final int VOID = 4;
  public static final int READOP = 33;
  public static final int RCURLY = 12;
  public static final int TIMES = 25;
  public static final int COLON = 17;
  public static final int ELSE = 42;
  public static final int LSQUARE = 15;
  public static final int WHILE = 43;
  public static final int RSQUARE = 16;
  public static final int GREATEREQ = 30;
  public static final int FALSE = 10;
  public static final int STRUCT = 5;
  public static final int NOTEQ = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "INTEGER",
  "VOID",
  "STRUCT",
  "ID",
  "INTLIT",
  "STRINGLIT",
  "TRUE",
  "FALSE",
  "LCURLY",
  "RCURLY",
  "LPAREN",
  "RPAREN",
  "LSQUARE",
  "RSQUARE",
  "COLON",
  "COMMA",
  "DOT",
  "AND",
  "OR",
  "NOT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "EQUALS",
  "NOTEQ",
  "GREATER",
  "GREATEREQ",
  "LESS",
  "LESSEQ",
  "READOP",
  "WRITEOP",
  "ASSIGN",
  "PLUSPLUS",
  "MINUSMINUS",
  "RETURN",
  "INPUT",
  "DISPLAY",
  "IF",
  "ELSE",
  "WHILE",
  "UMINUS"
  };
}

